name: challenge 1

on: push

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: date
  job2:
    name: Job 2
    runs-on: windows-latest
    steps:
      - name: Print Date
        run: Get-Date
  job3:
    name: Job 3
    runs-on: macos-latest
    steps:
      - name: Print Date
        run: date
  job4:
    runs-on: ubuntu-latest
    needs: [job1,job2,job3]
    steps:
      - name: Print Date
        run: date